language: C

addons:
  apt:
    packages:
      - apt-utils wget git build-essential
      - gfortran
      - mpich
      - libmpich-dev
      - libgsl0-dbg
      - libgsl0-dev

before_install:
  - sudo mkdir -p /usr/local/hdf5-parallel
  - wget --quiet https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.21/src/hdf5-1.8.21.tar.gz
  - tar -xzf hdf5-1.8.21.tar.gz
  - cd hdf5-1.8.21
  - FC=mpif90 CC=mpicc ./configure --enable-parallel --enable-fortran --prefix=/usr/local/hdf5-parallel
  - make -sj
  - sudo make -s install
  - cd ..
  - export CC=/usr/local/hdf5-parallel/bin/h5pcc
  - export FC=/usr/local/hdf5-parallel/bin/h5pfc
  - wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - sudo bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/local/miniconda3
  - sudo /usr/local/miniconda3/bin/conda install --yes --quiet numpy scipy h5py matplotlib pip psutil
  - sudo mkdir -p /usr/local/bin
  - sudo ln -s /usr/local/miniconda3/bin/python /usr/local/bin/python
  - export PATH=/usr/local/bin:${PATH}
  - mkdir -p ${HOME}/.config/matplotlib
  - cp script/dependencies/matplotlibrc ${HOME}/.config/matplotlib

script:
  - pwd
  - cd test
  - python tracers1d.py -fast
  - python test_all.py -fast
